-- ============================================================
-- 19 · REPORTES GUARDADOS POR FECHA
--
-- Cada vez que alguien imprime un reporte desde la app, se guarda una copia
-- exacta de lo que salió en el papel (período, máquina, quién y cuándo).
-- Después se puede volver a abrir o reimprimir desde Reportes → 📁 Guardados,
-- aunque los datos se hayan corregido después: la copia queda como se imprimió.
--
-- Las copias no se modifican ni se borran desde la app. Si el mismo reporte se
-- imprime dos veces el mismo día sin cambios, se guarda una sola vez (huella).
--
-- Correr ENTERO en el SQL Editor de Supabase. Se puede repetir sin riesgo.
-- ============================================================

create table if not exists reportes_guardados (
  id bigint generated by default as identity primary key,
  empresa text not null default 'Coop El Circulo',
  desde date not null,
  hasta date not null,
  maquina text not null default 'Todas',
  html text not null,
  huella text not null,
  emitido_por text default '',
  emitido_en timestamptz not null default now()
);

create unique index if not exists reportes_guardados_huella_idx
  on reportes_guardados (empresa, huella);
create index if not exists reportes_guardados_fecha_idx
  on reportes_guardados (empresa, emitido_en desc);

alter table reportes_guardados enable row level security;

-- Se pueden leer y agregar; no hay permiso para modificar ni borrar.
drop policy if exists "reportes_guardados_leer" on reportes_guardados;
create policy "reportes_guardados_leer" on reportes_guardados
  for select to authenticated using (true);
drop policy if exists "reportes_guardados_agregar" on reportes_guardados;
create policy "reportes_guardados_agregar" on reportes_guardados
  for insert to authenticated with check (true);

grant select, insert on reportes_guardados to authenticated;

-- Control: tiene que decir "tabla lista" y 0 reportes la primera vez.
select 'tabla lista' as estado, count(*) as reportes_guardados from reportes_guardados;
