-- ============================================================
-- Extensión para la app "Planta Rolleras" (coop el circulo):
-- login de operarios + bitácora de roturas/repuestos/insumos.
-- Correr DESPUÉS de 1-supabase-schema.sql, en el mismo proyecto.
-- ============================================================

-- La app necesita leer la tabla maquinas directamente (id real en uuid,
-- no solo el código vía las vistas) para poder referenciar eventos.
alter table maquinas enable row level security;
drop policy if exists "maquinas_select_authenticated" on maquinas;
create policy "maquinas_select_authenticated" on maquinas
  for select using (auth.role() = 'authenticated');

-- Notas libres por máquina (mantenimiento, observaciones) — no la usa el
-- pipeline de ingesta, es solo para esta app.
alter table maquinas add column if not exists notas text default '';

-- ---------- Login (Supabase Auth) ----------
create table if not exists usuarios (
  id bigint generated by default as identity primary key,
  nombre text not null,
  user_id uuid unique references auth.users(id) on delete cascade,
  activo boolean not null default true,
  created_at timestamptz default now()
);
alter table usuarios enable row level security;
drop policy if exists "usuarios_select_authenticated" on usuarios;
create policy "usuarios_select_authenticated" on usuarios
  for select using (auth.role() = 'authenticated');

-- ---------- Bitácora de eventos de máquina ----------
create table if not exists eventos_maquina (
  id bigint generated by default as identity primary key,
  maquina_id uuid not null references maquinas(id) on delete cascade,
  tipo text not null check (tipo in ('rotura','repuesto','insumo')),
  descripcion text not null,
  fecha date not null default current_date,
  resuelto boolean not null default false,
  resuelto_fecha date,
  creado_por text default '',
  created_at timestamptz default now()
);
alter table eventos_maquina enable row level security;
drop policy if exists "eventos_maquina_all_authenticated" on eventos_maquina;
create policy "eventos_maquina_all_authenticated" on eventos_maquina
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- ---------- Empresa / planta de coop el circulo ----------
-- El flujo de ingesta (n8n) debe mandar "empresa":"Coop El Circulo" y
-- "planta":"Rolleras" en el JSON que valida (nodo ValidarDatos), para que
-- las hojas de control de esta planta no se mezclen con otras empresas.
insert into empresas (nombre) values ('Coop El Circulo') on conflict do nothing;
insert into plantas (empresa_id, nombre)
  select id, 'Rolleras' from empresas where nombre = 'Coop El Circulo'
  on conflict do nothing;

-- ---------- Primer usuario ----------
-- Después de crear el usuario en Authentication > Users (Supabase), corré:
--   insert into usuarios (nombre, user_id) values ('Tu Nombre', 'UUID-DEL-USUARIO');
