-- ============================================================
-- 21 · CATALOGO DE PRODUCTOS POR CLIENTE
--
-- Hoy la medida se escribe a mano en cada lugar ("45x60x20x24", "45×60×20×24",
-- "45x60x20x24 (OLIVETO)", "60 x 90 x 10 x 24") y todo lo demas se adivina de
-- ese texto. Con el catalogo cada producto se carga UNA vez:
--
--   cliente · ancho x largo · bolsas por rollo · rollos por bulto · micras
--
-- y de ahi sale solo: la medida escrita siempre igual, los millares de bolsas,
-- el peso teorico de la bolsa (para controlar el calibre) y los kg por millar.
--
-- Peso teorico de una bolsa (en gramos):
--   ancho(cm) x largo(cm) x 2 caras x micras / 10000 x densidad(0,92 PEBD)
--   Ej: 45 x 60 x 2 x 25 micras / 10000 x 0,92 = 12,4 g
--
-- Correr ENTERO en el SQL Editor de Supabase. Se puede repetir sin riesgo.
-- ============================================================

create table if not exists productos (
  id bigint generated by default as identity primary key,
  empresa text not null default 'Coop El Circulo',
  cliente text not null,
  medida text not null,                 -- texto armado: "45x60x20x24"
  ancho_cm numeric,
  largo_cm numeric,
  bolsas_por_rollo int,
  rollos_por_bulto int,
  micras numeric,
  material text default 'PEBD',
  peso_bolsa_g numeric,                 -- teorico, para controlar el calibre
  notas text default '',
  activo boolean not null default true,
  creado_por text default '',
  creado_en timestamptz not null default now()
);

create unique index if not exists productos_cliente_medida_idx
  on productos (empresa, cliente, medida);
create index if not exists productos_cliente_idx on productos (empresa, cliente);

alter table productos enable row level security;

drop policy if exists "productos_todo_auth" on productos;
create policy "productos_todo_auth" on productos
  for all to authenticated using (true) with check (true);

grant select, insert, update, delete on productos to authenticated;

-- Control: tiene que decir "tabla lista" y 0 productos la primera vez.
select 'tabla lista' as estado, count(*) as productos from productos;
