-- ============================================================
-- 23 · STOCK DE INSUMOS (ETIQUETAS, CINTAS, BOBINAS DE PAPEL...)
--
-- Todo lo que se gasta en la planta en un solo lugar. Dos tablas:
--
--   insumos            lo que se controla (etiquetas Dottiplast, cinta, etc.)
--   movimientos_insumo cada entrada (+) y cada gasto (-)
--
-- El stock NO se guarda como un número que se pisa: se calcula sumando los
-- movimientos. Así queda el historial de quién gastó qué y cuándo, y si alguien
-- se equivoca se corrige con otro movimiento en vez de perder el dato.
--
-- Correr ENTERO en el SQL Editor de Supabase. Se puede repetir sin riesgo.
-- ============================================================

create table if not exists insumos (
  id bigint generated by default as identity primary key,
  empresa text not null default 'Coop El Circulo',
  nombre text not null,
  unidad text not null default 'unidades',   -- rollos, cajas, metros, unidades
  minimo numeric not null default 0,         -- avisar cuando baja de acá
  notas text default '',
  activo boolean not null default true,
  creado_por text default '',
  creado_en timestamptz not null default now()
);

create unique index if not exists insumos_nombre_idx on insumos (empresa, nombre);

create table if not exists movimientos_insumo (
  id bigint generated by default as identity primary key,
  insumo_id bigint not null references insumos(id) on delete cascade,
  cantidad numeric not null,                 -- positivo entra, negativo se gasta
  motivo text default '',
  creado_por text default '',
  creado_en timestamptz not null default now()
);

create index if not exists movimientos_insumo_idx
  on movimientos_insumo (insumo_id, creado_en desc);

-- Lo que hay ahora de cada insumo, con el último movimiento.
create or replace view v_insumos as
select i.id, i.empresa, i.nombre, i.unidad, i.minimo, i.notas, i.activo,
       coalesce(sum(m.cantidad), 0) as stock,
       max(m.creado_en) as ultimo_movimiento,
       count(m.id) as movimientos
  from insumos i
  left join movimientos_insumo m on m.insumo_id = i.id
 group by i.id;

alter table insumos enable row level security;
alter table movimientos_insumo enable row level security;

drop policy if exists "insumos_todo_auth" on insumos;
create policy "insumos_todo_auth" on insumos
  for all to authenticated using (true) with check (true);

-- Los movimientos se agregan y se leen, pero no se editan ni se borran:
-- es el historial de lo que se gastó.
drop policy if exists "movimientos_leer_auth" on movimientos_insumo;
create policy "movimientos_leer_auth" on movimientos_insumo
  for select to authenticated using (true);
drop policy if exists "movimientos_agregar_auth" on movimientos_insumo;
create policy "movimientos_agregar_auth" on movimientos_insumo
  for insert to authenticated with check (true);

grant select, insert, update, delete on insumos to authenticated;
grant select, insert on movimientos_insumo to authenticated;
grant select on v_insumos to authenticated;

-- Control: tiene que decir "tablas listas" y 0 insumos la primera vez.
select 'tablas listas' as estado, count(*) as insumos from insumos;
