-- ============================================================
-- MONITOREO EN VIVO DE MÁQUINAS
-- Correr en el SQL Editor de Supabase (una sola vez, después de SUPABASE-COMPLETO.sql).
-- ============================================================

-- Cada fila es un tramo: la máquina estuvo en tal estado desde `inicio` hasta `fin`.
-- El tramo con `fin` NULL es lo que está pasando AHORA.
create table if not exists estados_maquina (
  id bigint generated by default as identity primary key,
  maquina_id uuid not null references maquinas(id) on delete cascade,
  estado text not null check (estado in ('produciendo','parada','apagada')),
  medida text default '',          -- ej: 45x60x20
  presentacion text default '',    -- ej: a granel / x24 Dottiplast
  motivo text default '',          -- solo si está parada: cambio de cinta, repuesto...
  inicio timestamptz not null default now(),
  fin timestamptz,
  creado_por text default '',
  created_at timestamptz default now()
);

create index if not exists estados_maquina_idx on estados_maquina (maquina_id, inicio desc);

-- Una sola máquina no puede tener dos tramos abiertos a la vez.
create unique index if not exists estados_maquina_abierto_uk
  on estados_maquina (maquina_id) where fin is null;

alter table estados_maquina enable row level security;
drop policy if exists "estados_maquina_all_auth" on estados_maquina;
create policy "estados_maquina_all_auth" on estados_maquina
  for all to authenticated using (true) with check (true);

-- Cambiar el estado: cierra el tramo anterior y abre uno nuevo, en una sola operación.
create or replace function cambiar_estado_maquina(
  _maquina_id uuid,
  _estado text,
  _medida text default '',
  _presentacion text default '',
  _motivo text default '',
  _creado_por text default ''
) returns bigint
language plpgsql
as $$
declare v_id bigint;
begin
  update estados_maquina set fin = now()
   where maquina_id = _maquina_id and fin is null;

  insert into estados_maquina (maquina_id, estado, medida, presentacion, motivo, creado_por)
  values (_maquina_id, _estado, coalesce(_medida,''), coalesce(_presentacion,''),
          coalesce(_motivo,''), coalesce(_creado_por,''))
  returning id into v_id;

  return v_id;
end $$;

grant execute on function cambiar_estado_maquina(uuid, text, text, text, text, text) to authenticated;

-- ---------- ALTA MANUAL DE MÁQUINAS ----------
-- Normalmente las máquinas se crean solas cuando n8n procesa una hoja de control,
-- pero hace falta poder darlas de alta a mano para empezar a usar el monitoreo.
drop policy if exists "maquinas_insert_auth" on maquinas;
create policy "maquinas_insert_auth" on maquinas
  for insert to authenticated with check (true);

drop policy if exists "maquinas_delete_auth" on maquinas;
create policy "maquinas_delete_auth" on maquinas
  for delete to authenticated using (true);

-- Resuelve empresa y planta solo, así la app no necesita saber los uuid.
create or replace function crear_maquina(_codigo text, _nombre text default '')
returns uuid
language plpgsql
security definer
as $$
declare v_emp uuid; v_pla uuid; v_id uuid;
begin
  insert into empresas (nombre) values ('Coop El Circulo') on conflict (nombre) do nothing;
  select id into v_emp from empresas where nombre = 'Coop El Circulo';

  insert into plantas (empresa_id, nombre) values (v_emp, 'Rolleras')
    on conflict (empresa_id, nombre) do nothing;
  select id into v_pla from plantas where empresa_id = v_emp and nombre = 'Rolleras';

  insert into maquinas (planta_id, codigo, nombre)
  values (v_pla, trim(_codigo), coalesce(_nombre,''))
  on conflict (planta_id, codigo) do update set nombre = excluded.nombre
  returning id into v_id;

  return v_id;
end $$;

grant execute on function crear_maquina(text, text) to authenticated;

-- Vista: qué está haciendo cada máquina ahora mismo.
create or replace view v_estado_actual as
select m.id as maquina_id, m.codigo as maquina, m.nombre as maquina_nombre, m.activa,
       e.id as estado_id, e.estado, e.medida, e.presentacion, e.motivo,
       e.inicio, e.creado_por
from maquinas m
left join estados_maquina e on e.maquina_id = m.id and e.fin is null;

grant select on v_estado_actual to authenticated;
