-- ============================================================
-- COOP EL CIRCULO — PLANTA ROLLERAS
-- Esquema completo: producción (hojas de control vía n8n) + app de planta.
-- Pegar TODO esto en el SQL Editor de Supabase y ejecutar UNA sola vez.
-- ============================================================

create extension if not exists pgcrypto;

-- ---------- TABLAS ----------

create table if not exists empresas (
  id uuid primary key default gen_random_uuid(),
  nombre text not null unique,
  creado_en timestamptz not null default now()
);

create table if not exists plantas (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references empresas(id) on delete cascade,
  nombre text not null,
  unique (empresa_id, nombre)
);

create table if not exists maquinas (
  id uuid primary key default gen_random_uuid(),
  planta_id uuid not null references plantas(id) on delete cascade,
  codigo text not null,
  nombre text,
  activa boolean not null default true,
  notas text default '',
  unique (planta_id, codigo)
);

create table if not exists operarios (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references empresas(id) on delete cascade,
  nombre text not null,
  iniciales text,
  activo boolean not null default true,
  unique (empresa_id, nombre)
);

create table if not exists defectos (
  id serial primary key,
  nombre text not null unique
);

-- Un parte de produccion = una hoja de control (maquina + fecha + turno)
create table if not exists producciones (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references empresas(id),
  planta_id uuid not null references plantas(id),
  maquina_id uuid not null references maquinas(id),
  operario_id uuid references operarios(id),
  fecha date not null,
  turno text not null check (turno in ('dia','noche')),
  medida text,
  filas int,
  bultos int,
  observaciones text,
  origen text,
  creado_en timestamptz not null default now(),
  unique (maquina_id, fecha, turno)
);

-- Cada bobina es un registro independiente
create table if not exists bobinas (
  id uuid primary key default gen_random_uuid(),
  produccion_id uuid not null references producciones(id) on delete cascade,
  n_bobina text not null,
  peso numeric,
  iniciales text,
  operario_id uuid references operarios(id),
  estado text check (estado in ('BIEN','MAL')),
  unique (produccion_id, n_bobina)
);

create table if not exists bobina_defectos (
  bobina_id uuid not null references bobinas(id) on delete cascade,
  defecto_id int not null references defectos(id),
  detalle text,
  primary key (bobina_id, defecto_id)
);

create table if not exists scrap (
  id uuid primary key default gen_random_uuid(),
  produccion_id uuid not null unique references producciones(id) on delete cascade,
  empalme numeric not null default 0,
  rollo numeric not null default 0
);

create table if not exists historial (
  id bigint generated always as identity primary key,
  empresa_id uuid references empresas(id),
  evento text not null,
  detalle jsonb,
  creado_en timestamptz not null default now()
);

-- ---------- TABLAS DE LA APP DE PLANTA ----------

-- Login: cada persona que usa la app (se vincula a Supabase Auth)
create table if not exists usuarios (
  id bigint generated by default as identity primary key,
  nombre text not null,
  user_id uuid unique references auth.users(id) on delete cascade,
  activo boolean not null default true,
  created_at timestamptz default now()
);

-- Bitácora: roturas, repuestos e insumos faltantes por máquina
create table if not exists eventos_maquina (
  id bigint generated by default as identity primary key,
  maquina_id uuid not null references maquinas(id) on delete cascade,
  tipo text not null check (tipo in ('rotura','repuesto','insumo')),
  descripcion text not null,
  fecha date not null default current_date,
  resuelto boolean not null default false,
  resuelto_fecha date,
  creado_por text default '',
  created_at timestamptz default now()
);

-- ---------- VISTAS (estadisticas siempre en tiempo real) ----------

create or replace view v_bobinas as
select
  b.id, p.empresa_id, e.nombre as empresa, pl.nombre as planta,
  m.codigo as maquina, p.fecha, p.turno, p.medida,
  op.nombre as operario_turno,
  coalesce(ob.nombre, b.iniciales) as operario_bobina,
  b.n_bobina, b.peso, b.estado,
  (select string_agg(coalesce(bd.detalle, d.nombre), ', ')
     from bobina_defectos bd left join defectos d on d.id = bd.defecto_id
    where bd.bobina_id = b.id) as defectos,
  p.id as produccion_id
from bobinas b
join producciones p on p.id = b.produccion_id
join empresas e on e.id = p.empresa_id
join plantas pl on pl.id = p.planta_id
join maquinas m on m.id = p.maquina_id
left join operarios op on op.id = p.operario_id
left join operarios ob on ob.id = b.operario_id;

create or replace view v_producciones as
select
  p.id, p.empresa_id, e.nombre as empresa, pl.nombre as planta,
  m.codigo as maquina, o.nombre as operario,
  p.fecha, p.turno, p.medida, p.filas, p.bultos, p.observaciones,
  (select count(*) from bobinas b where b.produccion_id = p.id) as bobinas,
  (select coalesce(sum(peso),0) from bobinas b where b.produccion_id = p.id) as kilos,
  (select count(*) from bobinas b where b.produccion_id = p.id and estado = 'BIEN') as bien,
  (select count(*) from bobinas b where b.produccion_id = p.id and estado = 'MAL') as mal,
  coalesce(s.empalme,0) as scrap_empalme,
  coalesce(s.rollo,0) as scrap_rollo
from producciones p
join empresas e on e.id = p.empresa_id
join plantas pl on pl.id = p.planta_id
join maquinas m on m.id = p.maquina_id
left join operarios o on o.id = p.operario_id
left join scrap s on s.produccion_id = p.id;

create or replace view v_produccion_diaria as
select empresa_id, empresa, fecha,
  sum(bobinas) as bobinas, sum(kilos) as kilos,
  case when sum(bobinas) > 0 then round(sum(kilos)/sum(bobinas),1) end as peso_promedio,
  sum(bien) as bien, sum(mal) as mal, sum(bultos) as bultos,
  sum(scrap_empalme) as scrap_empalme, sum(scrap_rollo) as scrap_rollo,
  case when sum(kilos) > 0 then round(100*(sum(scrap_empalme)+sum(scrap_rollo))/sum(kilos),2) end as scrap_pct
from v_producciones
group by empresa_id, empresa, fecha;

create or replace view v_produccion_semanal as
select empresa_id, empresa, date_trunc('week', fecha)::date as semana,
  sum(bobinas) as bobinas, sum(kilos) as kilos,
  case when sum(bobinas) > 0 then round(sum(kilos)/sum(bobinas),1) end as peso_promedio,
  sum(bien) as bien, sum(mal) as mal, sum(bultos) as bultos,
  sum(scrap_empalme) as scrap_empalme, sum(scrap_rollo) as scrap_rollo,
  case when sum(kilos) > 0 then round(100*(sum(scrap_empalme)+sum(scrap_rollo))/sum(kilos),2) end as scrap_pct
from v_producciones
group by empresa_id, empresa, date_trunc('week', fecha);

create or replace view v_produccion_mensual as
select empresa_id, empresa, date_trunc('month', fecha)::date as mes,
  sum(bobinas) as bobinas, sum(kilos) as kilos,
  case when sum(bobinas) > 0 then round(sum(kilos)/sum(bobinas),1) end as peso_promedio,
  sum(bien) as bien, sum(mal) as mal, sum(bultos) as bultos,
  sum(scrap_empalme) as scrap_empalme, sum(scrap_rollo) as scrap_rollo,
  case when sum(kilos) > 0 then round(100*(sum(scrap_empalme)+sum(scrap_rollo))/sum(kilos),2) end as scrap_pct
from v_producciones
group by empresa_id, empresa, date_trunc('month', fecha);

create or replace view v_por_maquina as
select empresa_id, empresa, maquina,
  sum(bobinas) as bobinas, sum(kilos) as kilos, sum(bien) as bien, sum(mal) as mal,
  sum(scrap_empalme) as scrap_empalme, sum(scrap_rollo) as scrap_rollo,
  case when sum(kilos) > 0 then round(100*(sum(scrap_empalme)+sum(scrap_rollo))/sum(kilos),2) end as scrap_pct
from v_producciones
group by empresa_id, empresa, maquina;

create or replace view v_por_operario as
select p.empresa_id, empresa, coalesce(operario_bobina,'S/D') as operario,
  count(*) as bobinas, coalesce(sum(peso),0) as kilos,
  count(*) filter (where estado = 'BIEN') as bien,
  count(*) filter (where estado = 'MAL') as mal
from v_bobinas p
group by p.empresa_id, empresa, coalesce(operario_bobina,'S/D');

create or replace view v_por_turno as
select empresa_id, empresa, turno,
  sum(bobinas) as bobinas, sum(kilos) as kilos, sum(bien) as bien, sum(mal) as mal,
  sum(scrap_empalme) as scrap_empalme, sum(scrap_rollo) as scrap_rollo
from v_producciones
group by empresa_id, empresa, turno;

create or replace view v_defectos as
select p.empresa_id, e.nombre as empresa, p.fecha, m.codigo as maquina,
  coalesce(d.nombre, bd.detalle, 'sin detalle') as defecto, count(*) as cantidad
from bobina_defectos bd
left join defectos d on d.id = bd.defecto_id
join bobinas b on b.id = bd.bobina_id
join producciones p on p.id = b.produccion_id
join empresas e on e.id = p.empresa_id
join maquinas m on m.id = p.maquina_id
group by p.empresa_id, e.nombre, p.fecha, m.codigo, coalesce(d.nombre, bd.detalle, 'sin detalle');

create or replace view v_scrap as
select p.empresa_id, e.nombre as empresa, m.codigo as maquina, p.fecha, p.turno,
  s.empalme, s.rollo, s.empalme + s.rollo as total
from scrap s
join producciones p on p.id = s.produccion_id
join empresas e on e.id = p.empresa_id
join maquinas m on m.id = p.maquina_id;

-- ---------- RPC: carga transaccional de un parte ----------
-- n8n llama esta funcion con el JSON validado. Resuelve/crea empresa,
-- planta, maquina y operarios; inserta produccion, bobinas (sin duplicar),
-- defectos y scrap; registra historial. Devuelve advertencias.

create or replace function cargar_parte(datos jsonb)
returns jsonb
language plpgsql
security definer
as $$
declare
  v_emp uuid; v_pla uuid; v_maq uuid; v_op uuid; v_prod uuid;
  v_bob uuid; v_def int; v_opb uuid;
  v_nombre_emp text; v_nombre_pla text; v_cod_maq text; v_nombre_op text;
  adv text[] := '{}';
  b jsonb;
  ins int := 0;
begin
  v_nombre_emp := coalesce(nullif(datos->>'empresa',''),'Coop El Circulo');
  insert into empresas (nombre) values (v_nombre_emp) on conflict (nombre) do nothing;
  v_emp := (select id from empresas where nombre = v_nombre_emp);

  v_nombre_pla := coalesce(nullif(datos->>'planta',''),'Rolleras');
  insert into plantas (empresa_id, nombre) values (v_emp, v_nombre_pla) on conflict (empresa_id, nombre) do nothing;
  v_pla := (select id from plantas where empresa_id = v_emp and nombre = v_nombre_pla);

  v_cod_maq := coalesce(nullif(datos->>'maquina',''),'S/D');
  insert into maquinas (planta_id, codigo) values (v_pla, v_cod_maq) on conflict (planta_id, codigo) do nothing;
  v_maq := (select id from maquinas where planta_id = v_pla and codigo = v_cod_maq);

  v_nombre_op := coalesce(nullif(datos->>'operario',''),'S/D');
  insert into operarios (empresa_id, nombre) values (v_emp, v_nombre_op) on conflict (empresa_id, nombre) do nothing;
  v_op := (select id from operarios where empresa_id = v_emp and nombre = v_nombre_op);

  v_prod := (select id from producciones
              where maquina_id = v_maq and fecha = (datos->>'fecha')::date and turno = datos->>'turno');

  if v_prod is not null then
    adv := adv || 'Ya existia un parte para esa maquina, fecha y turno: se agregan solo las bobinas nuevas';
  else
    insert into producciones (empresa_id, planta_id, maquina_id, operario_id, fecha, turno,
                              medida, filas, bultos, observaciones, origen)
    values (v_emp, v_pla, v_maq, v_op, (datos->>'fecha')::date, datos->>'turno',
            datos->>'medida', nullif(datos->>'filas','')::int, nullif(datos->>'bultos','')::int,
            datos->>'observaciones', datos->>'origen');
    v_prod := (select id from producciones
                where maquina_id = v_maq and fecha = (datos->>'fecha')::date and turno = datos->>'turno');
  end if;

  for b in select * from jsonb_array_elements(coalesce(datos->'bobinas','[]'::jsonb)) loop
    if exists (select 1 from bobinas where produccion_id = v_prod and n_bobina = b->>'n_bobina') then
      adv := adv || ('Bobina repetida (ya estaba cargada): ' || (b->>'n_bobina'));
      continue;
    end if;

    v_opb := null;
    if coalesce(b->>'iniciales','') <> '' then
      v_opb := (select id from operarios
                 where empresa_id = v_emp
                   and (upper(coalesce(iniciales,'')) = upper(b->>'iniciales') or upper(nombre) = upper(b->>'iniciales'))
                 limit 1);
      if v_opb is null then
        insert into operarios (empresa_id, nombre, iniciales)
        values (v_emp, upper(b->>'iniciales'), upper(b->>'iniciales'))
        on conflict (empresa_id, nombre) do nothing;
        v_opb := (select id from operarios where empresa_id = v_emp and nombre = upper(b->>'iniciales'));
      end if;
    end if;

    insert into bobinas (produccion_id, n_bobina, peso, iniciales, operario_id, estado)
    values (v_prod, b->>'n_bobina', nullif(b->>'peso','')::numeric,
            nullif(upper(coalesce(b->>'iniciales','')),''), v_opb,
            nullif(upper(coalesce(b->>'estado','')),''));
    v_bob := (select id from bobinas where produccion_id = v_prod and n_bobina = b->>'n_bobina');
    ins := ins + 1;

    if coalesce(b->>'defecto','') <> '' then
      insert into defectos (nombre) values (lower(trim(b->>'defecto')))
        on conflict (nombre) do nothing;
      v_def := (select id from defectos where nombre = lower(trim(b->>'defecto')));
      insert into bobina_defectos (bobina_id, defecto_id, detalle)
      values (v_bob, v_def, b->>'defecto')
      on conflict do nothing;
    end if;
  end loop;

  if (datos ? 'scrap_empalme') or (datos ? 'scrap_rollo') then
    insert into scrap (produccion_id, empalme, rollo)
    values (v_prod, coalesce((datos->>'scrap_empalme')::numeric,0), coalesce((datos->>'scrap_rollo')::numeric,0))
    on conflict (produccion_id) do update set empalme = excluded.empalme, rollo = excluded.rollo;
  end if;

  insert into historial (empresa_id, evento, detalle)
  values (v_emp, 'carga_parte',
          jsonb_build_object('produccion_id', v_prod, 'bobinas_insertadas', ins,
                             'advertencias', to_jsonb(adv), 'origen', datos->>'origen'));

  return jsonb_build_object('ok', true, 'produccion_id', v_prod,
                            'bobinas_insertadas', ins, 'advertencias', to_jsonb(adv));
end $$;

-- ---------- RPC: consultas de solo lectura para el agente IA ----------

create or replace function consulta_lectura(sql text)
returns jsonb
language plpgsql
security definer
as $$
declare
  resultado jsonb;
  limpio text;
begin
  limpio := regexp_replace(trim(sql), ';\s*$', '');
  if limpio !~* '^\s*select' then
    raise exception 'Solo se permiten consultas SELECT';
  end if;
  if position(';' in limpio) > 0 then
    raise exception 'No se permiten multiples sentencias';
  end if;
  if limpio ~* '\m(insert|update|delete|drop|alter|create|grant|revoke|truncate|copy)\M' then
    raise exception 'Solo se permiten consultas de lectura';
  end if;
  execute 'set local statement_timeout = ''5s''';
  execute format('select coalesce(jsonb_agg(t), ''[]''::jsonb) from (%s) t', limpio)
    into resultado;
  return resultado;
end $$;

-- ---------- SEGURIDAD ----------
-- n8n escribe con la service_role key (pasa por encima de RLS).
-- La app lee las vistas y, con usuario logueado, las tablas que necesita.

alter table empresas enable row level security;
alter table plantas enable row level security;
alter table maquinas enable row level security;
alter table operarios enable row level security;
alter table defectos enable row level security;
alter table producciones enable row level security;
alter table bobinas enable row level security;
alter table bobina_defectos enable row level security;
alter table scrap enable row level security;
alter table historial enable row level security;
alter table usuarios enable row level security;
alter table eventos_maquina enable row level security;

-- La app arma el listado de máquinas con un join maquinas → plantas → empresas,
-- así que las tres necesitan permiso de lectura para el usuario logueado.
drop policy if exists "empresas_select_auth" on empresas;
create policy "empresas_select_auth" on empresas
  for select to authenticated using (true);

drop policy if exists "plantas_select_auth" on plantas;
create policy "plantas_select_auth" on plantas
  for select to authenticated using (true);

drop policy if exists "maquinas_select_auth" on maquinas;
create policy "maquinas_select_auth" on maquinas
  for select to authenticated using (true);

-- La app puede editar nombre/notas/estado de la máquina (no crearlas ni borrarlas:
-- se crean solas al procesar cada hoja de control).
drop policy if exists "maquinas_update_auth" on maquinas;
create policy "maquinas_update_auth" on maquinas
  for update to authenticated using (true) with check (true);

drop policy if exists "usuarios_select_auth" on usuarios;
create policy "usuarios_select_auth" on usuarios
  for select to authenticated using (true);

-- Bitácora de eventos: los usuarios logueados cargan, resuelven y borran.
drop policy if exists "eventos_maquina_all_auth" on eventos_maquina;
create policy "eventos_maquina_all_auth" on eventos_maquina
  for all to authenticated using (true) with check (true);

grant select on v_bobinas, v_producciones, v_produccion_diaria, v_produccion_semanal,
                v_produccion_mensual, v_por_maquina, v_por_operario, v_por_turno,
                v_defectos, v_scrap
to anon, authenticated;

revoke execute on function cargar_parte(jsonb) from anon, authenticated;
revoke execute on function consulta_lectura(text) from anon, authenticated;

-- ---------- DATOS INICIALES ----------
insert into empresas (nombre) values ('Coop El Circulo') on conflict do nothing;
insert into plantas (empresa_id, nombre)
  select id, 'Rolleras' from empresas where nombre = 'Coop El Circulo'
  on conflict do nothing;
insert into defectos (nombre) values ('arrugas'), ('fuelle'), ('grueso'), ('corrido') on conflict do nothing;

-- ============================================================
-- DESPUÉS DE CORRER ESTO:
-- 1. Authentication → Users → Add user (email y contraseña para entrar a la app).
-- 2. Copiar el UUID del usuario creado y correr acá:
--      insert into usuarios (nombre, user_id) values ('Tu Nombre', 'PEGAR-UUID');
-- 3. Repetir por cada persona que use la app.
-- ============================================================
